---
- hosts: all
  become: no
  gather_facts: no
  tasks:
    - name: Firewall rule - allow incoming port
      iptables: action=insert state=present chain=INPUT destination_port={{incomingport}} jump=ACCEPT protocol={{protocol}}